name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: helloapp
  REGISTRY: ghcr.io

jobs:
  test:
    name: Run Tests in Docker
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and run test stage
      run: |
        docker build --target test -t ${{ env.IMAGE_NAME }}:test .
        echo "✅ Tests passed in Docker container!"