name: CI Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  IMAGE_NAME: helloapp

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build test image
      run: docker build --target test -t ${{ env.IMAGE_NAME }}:test .

    - name: Run tests in container
      run: docker run --rm ${{ env.IMAGE_NAME }}:test ./test.sh

  build:
    name: Build Production Image
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build production image
      run: docker build --target production -t ${{ env.IMAGE_NAME }}:latest .
